### ISSUE TITLE
this script is only for nothing phone 1

### ISSUE THREAD

**Issue by Xellerate005** [sh4tteredd/nothing-phone-1-tools#5]
./flash_all.sh
nothing phone(1) fastboot flash by @sh4tteredd

DON'T flash a nothingOS version lower than that one that's currently installed on the phone!

In order to gather all the files that we need, consider to run my other script available on https://github.com/sh4tteredd/nothing-phone-1-tools

Instead, if you already have the .img files, put all your files in a subfolder called 'images' to continue

Now connect your phone in fastboot mode to the PC via USB, then press enter to continue
This script is only for nothing phone(1)

**Comment by JoelJoos** [comment]
+1
Downloaded image using the download.sh, then I wanted to flash it using flash_all.sh and the script returns " This script is only for nothing phone(1)"

**Comment by sh4tteredd** [comment]
I'm seeing this error frequently, it seems like that, at least with phones updated at the latest OS, the product name changes from the original "lahaina" to "Spacewar". It's pretty common. 
I can't get why or at what version is related, but the fix is very easy, I'll update the script asap. 
If you're hurry you can't just change the script and delete the first lines that check the device name.

**Comment by sh4tteredd** [comment]
I've actually fixed both versions (unix-like and Windows), if can anyone try those please give me a feedback :)

EDIT: I'm so sorry for @Xellerate005 but when you opened the issue I really didn't get what did you mean.

**Comment by JoelJoos** [comment]
@sh4tteredd Works like a charm! 
But I recommend changing the "Now connect your phone in fastboot mode to the PC via USB, then press enter to continue" prompt since the commands `adb reboot fastboot` and `adb reboot bootloader` result in different things. And for your script to work, you have to be in the bootloader, not fastboot.

**Comment by sh4tteredd** [comment]
@JoelJoos Thanks, you're right! I'll update.

Closing the issue, feel free to re-open in case
